version: '3'
services:
  server:
    container_name: debug_dev_server
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postpassword
      - PGDATABASE=trackit
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm start"
  db:
    container_name: debug_dev_db
    image: postgres:latest
    environment: 
      - POSTGRES_USER=postgres
    volumes:
      - "./db:/docker-entrypoint-initdb.d/:ro"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=trackit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpassword
volumes:
  dbdata:
networks: 
  default:
    name: debug_server